# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"storm": "01_stormtracks.ipynb"}

modules = ["storm.py"]

doc_url = "https://florianboergel.github.io/drcstools/"

git_url = "https://github.com/florianboergel/drcstools/tree/master/"

def custom_doc_links(name): return None
