# AUTOGENERATED! DO NOT EDIT! File to edit: 02_stats.ipynb (unless otherwise specified).

__all__ = ['regression', 'mean2', 'corr2']

# Cell
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt

# Cell
def regression(data, index):
    """
    Fast regression for spatial `data` onto 1d `index`.
    """

    data_flat = data.reshape(data.shape[0], np.product(data.shape[1:]))

    index = np.vstack((np.ones(len(index)), index)).T
    beta_hat = np.linalg.inv(index.T.dot(index)).dot(index.T).dot(data_flat)

    b0, b1 = beta_hat[0], beta_hat[1]
    b0 = b0.reshape((data.shape[1], data.shape[2]))
    b1 = b1.reshape((data.shape[1], data.shape[2]))

    return b0, b1

# Cell

def mean2(x):
    """Used for the corr2 function, according to Matlab.
    Args:
        x (float):
    Returns:
        y (float): mean of x
    """
    y = np.sum(x) / np.size(x);
    return y

def corr2(a,b):
    """
    According to Matlab corr2-function.
    """
    a = a - self.mean2(a)
    b = b - self.mean2(b)

    r = (a*b).sum() / math.sqrt((a*a).sum() * (b*b).sum());
    return r