# AUTOGENERATED! DO NOT EDIT! File to edit: 02_stats.ipynb (unless otherwise specified).

__all__ = ['regression', 'time', 'noise', 'data_vars', 'coords', 'dataset']

# Cell
import xarray as xr
import numpy as np

# Cell
def regression(data, index):
    """
    Fast regression for spatial `data` onto 1d `index`.
    """

    data_flat = data.reshape(data.shape[0], np.product(data.shape[1:]))

    index = np.vstack((np.ones(len(index)), index)).T
    beta_hat = np.linalg.inv(index.T.dot(index)).dot(index.T).dot(data_flat)

    b0, b1 = beta_hat[0], beta_hat[1]
    b0 = b0.reshape((data.shape[1], data.shape[2]))
    b1 = b1.reshape((data.shape[1], data.shape[2]))

    return b0, b1

# Cell

time = np.linspace(1, 100, 100)
lat, lon = np.ogrid[-45:45:50j, 0:360:100j]

noise = 5 * np.sin(np.random.randn(time.shape[0],
                                   lat.shape[0],
                                   lon.shape[1])/2*np.pi)

data_vars = {'noise': (['time', 'lat', 'lon'], noise)}
coords = {'time': time, 'lat': lat.ravel(), 'lon': lon.ravel()}
dataset = xr.Dataset(data_vars, coords)