# AUTOGENERATED! DO NOT EDIT! File to edit: 02_stats.ipynb (unless otherwise specified).

__all__ = ['regression']

# Cell
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt

# Cell
def regression(data, index):
    """
    Fast regression for spatial `data` onto 1d `index`.
    """

    data_flat = data.reshape(data.shape[0], np.product(data.shape[1:]))

    index = np.vstack((np.ones(len(index)), index)).T
    beta_hat = np.linalg.inv(index.T.dot(index)).dot(index.T).dot(data_flat)

    b0, b1 = beta_hat[0], beta_hat[1]
    b0 = b0.reshape((data.shape[1], data.shape[2]))
    b1 = b1.reshape((data.shape[1], data.shape[2]))

    return b0, b1